title: Sandipan Datta # your name (or website title) here
logo: "https://github.com/Sandipan254/Sandipan254.github.io/blob/master/IMG_20200226_210449%20(1).jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  2nd year Civil Engineering Undergrad 
  <br><br>
  IIEST Shibpur 
  <br><br>
  <a href="https://www.linkedin.com/in/sandipan-datta-368012188/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
